expandmem-objs	:=	expandmem_drv.o expandmem_vendor_hooks.o expandmem_impl.o \
					eswap_area.o eswap_impl.o eswap_list.o eswap_lru.o \
					eswap_manager.o eswap_schedule.o eswap_stats.o eswap_ctrl.o
obj-$(CONFIG_EXPANDMEM)	+=	expandmem.o